name: Auto approve
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD_LABELS: 'automerge=merge,autosquash=squash'
          MERGE_COMMIT_MESSAGE: 'pull-request-title'
          MERGE_METHOD: 'merge'
          MERGE_FORKS: 'true'
          MERGE_RETRIES: '10'
          MERGE_RETRY_SLEEP: '10000' # ten seconds
          UPDATE_LABELS: 'automerge,autosquash'
          UPDATE_METHOD: 'merge'
